# Site configuration

global:
  title:     "Okra App Framework"
  subtitle:  "The app centric MVVM framework for Windows and Windows Phone"

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  google_font: 'Open+Sans:400,700'

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

disqus:
  shortname:  okraframework

# Global Jekyll configuration

exclude:
- Gemfile

encoding: utf-8

paginate_path: 'blog/page:num/'
paginate: 10
